
project_id = "phgrwmrxcryhkkmjkpqc"

[functions.generate-content]
verify_jwt = true

[functions.analyze-subreddits]
verify_jwt = true

[functions.analyze-website] 
verify_jwt = true

[functions.generate-reddit-posts]
verify_jwt = true

[functions.chat-with-recommendations]
verify_jwt = false

