
[functions.analyze-subreddits]
verify_jwt = false

[functions.generate-reddit-posts]
verify_jwt = false

[functions.analyze-website]
verify_jwt = false

[functions.chat-with-recommendations]
verify_jwt = false

[functions.generate-content]
verify_jwt = false
